create table if not exists public.users (
    id text primary key,
    username text not null unique,
    password_hash text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.todos (
    id text primary key,
    user_id text not null references public.users(id) on delete cascade,
    task text not null,
    completed boolean not null default false,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.events (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null default timezone('utc', now()),
    ip text not null,
    endpoint text not null,
    method text not null,
    status_code integer not null,
    latency_ms numeric,
    username text,
    kind text not null,
    severity text not null,
    attack_type text,
    action text not null,
    detail text,
    blocked boolean not null default false,
    synthetic boolean not null default false,
    ml_score numeric
);

create table if not exists public.alerts (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null default timezone('utc', now()),
    ip text not null,
    attack_type text not null,
    severity text not null,
    action text not null,
    detail text,
    confidence numeric
);

alter table public.users enable row level security;
alter table public.todos enable row level security;
alter table public.events enable row level security;
alter table public.alerts enable row level security;

drop policy if exists users_demo_all on public.users;
drop policy if exists todos_demo_all on public.todos;
drop policy if exists events_demo_all on public.events;
drop policy if exists alerts_demo_all on public.alerts;

create policy users_demo_all on public.users for all to anon, authenticated using (true) with check (true);
create policy todos_demo_all on public.todos for all to anon, authenticated using (true) with check (true);
create policy events_demo_all on public.events for all to anon, authenticated using (true) with check (true);
create policy alerts_demo_all on public.alerts for all to anon, authenticated using (true) with check (true);
